name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write          # needed to push the generated file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Generate the SVG from your real contributions grid
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: JeffiProgrammer   # <-- change if your username differs
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Push the SVG to the 'output' branch (created automatically if missing)
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
